In [1]:
import numpy as np
from numpy.linalg import solve
import pandas as pd
import time
import sys
import csv
import math
import datetime
import itertools
import psutil
import random

In [8]:
def getTransitionProbability(N, R = 1):
    pr = np.zeros((R * N, R * N))
    for r in range(R):
        class_number = 0
        p = np.random.rand(N, N)
        for i, val in enumerate(np.sum(p, axis=1)):
            p[i] /= val
        for i in range(N):
            for j in range(N):
                pr[r * N+i,r * N+j] = p[i,j]
    return pr

In [3]:
"""
def getEquivalence(th, roop, p):
    list_number = 0 #空のリストを最初から使用する

    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)
    equivalence = [[] for i in range(len(p))] #同値類を最大数用意
    
    #2.Comunicationか判定して、Commnicateの場合リストに登録
    for ix in range(roop): #n乗まで実施
        p = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
        for i in range(len(p)):
            for j in range(i+1, len(p)):
                if(p[i][j] > th and p[j][i] > th): #推移確率が閾値より大きいかチェック
                    #3. communicateだった場合
                    find = 0 
                    for k in range(len(p)):
                        if i in equivalence[k]: #iが同値類k番目に存在している
                            find = 1 #iは同値類k番目に存在
                            if j not in equivalence[k]: #jは同値類kには存在しない
                                equivalence[k].append(j) #jを追加        
                            break
                        if j in equivalence[k]: 
                            find = 1 
                            if i not in equivalence[k]:
                                equivalence[k].append(i)        
                            break
                    if(find == 0): #新規に追加
                        equivalence[list_number].append(i)
                        if(i != j):
                            equivalence[list_number].append(j)
                        list_number += 1

    #4. Communicateにならないノードを登録
    for i in range(len(p)):
        find = 0
        for j in range(len(p)):
            if i in equivalence[j]:
                find = 1
                break
        if find == 0:
            equivalence[list_number].append(i)
            list_number += 1

    #5. エルゴード性の確認(class数が1のとき)
    class_number = 0
    for i in range(len(p)):
        if len(equivalence[i]) > 0:
            class_number += 1

    return equivalence, class_number
"""

'\ndef getEquivalence(th, roop, p):\n    list_number = 0 #空のリストを最初から使用する\n\n    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)\n    equivalence = [[] for i in range(len(p))] #同値類を最大数用意\n    \n    #2.Comunicationか判定して、Commnicateの場合リストに登録\n    for ix in range(roop): #n乗まで実施\n        p = np.linalg.matrix_power(p.copy(), ix+1) #累乗 \n        for i in range(len(p)):\n            for j in range(i+1, len(p)):\n                if(p[i][j] > th and p[j][i] > th): #推移確率が閾値より大きいかチェック\n                    #3. communicateだった場合\n                    find = 0 \n                    for k in range(len(p)):\n                        if i in equivalence[k]: #iが同値類k番目に存在している\n                            find = 1 #iは同値類k番目に存在\n                            if j not in equivalence[k]: #jは同値類kには存在しない\n                                equivalence[k].append(j) #jを追加        \n                            break\n                        if j in equivalence[k]: \n                            find = 1 \n                            

In [4]:
"""
def getEquivalence2(th, roop, p):
    list_number = 0 #空のリストを最初から使用する

    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)
    equivalence = [[] for i in range(len(p))] #同値類を最大数用意
    
    #2.Comunicationか判定して、Commnicateの場合リストに登録
    for ix in range(roop): #n乗まで実施
        print('ループ回数 {0}'.format(ix))
        pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
        print('推移確率 {0}'.format(pn))
        for i in range(len(pn)):
            for j in range(i+1, len(pn)):
                if(pn[i][j] > th and pn[j][i] > th): #推移確率が閾値より大きいかチェック
                    #3. communicateだった場合
                    print('Communicate {0} <-> {1}'.format(i, j))
                    find = 0 
                    for k in range(len(pn)):
                        if i in equivalence[k]: #iが同値類k番目に存在している
                            find = 1 #iは同値類k番目に存在
                            if j not in equivalence[k]: #jは同値類kには存在しない
                                equivalence[k].append(j) #jを追加        
                            break
                        if j in equivalence[k]: 
                            find = 1 
                            if i not in equivalence[k]:
                                equivalence[k].append(i)        
                            break
                    if(find == 0): #新規に追加
                        equivalence[list_number].append(i)
                        if(i != j):
                            equivalence[list_number].append(j)
                        list_number += 1

    #4. Communicateにならないノードを登録
    for i in range(len(pn)):
        find = 0
        for j in range(len(pn)):
            if i in equivalence[j]:
                find = 1
                break
        if find == 0:
            equivalence[list_number].append(i)
            list_number += 1

    #5. エルゴード性の確認(class数が1のとき)
    class_number = 0
    for i in range(len(p)):
        if len(equivalence[i]) > 0:
            class_number += 1

    return equivalence, class_number
"""

"\ndef getEquivalence2(th, roop, p):\n    list_number = 0 #空のリストを最初から使用する\n\n    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)\n    equivalence = [[] for i in range(len(p))] #同値類を最大数用意\n    \n    #2.Comunicationか判定して、Commnicateの場合リストに登録\n    for ix in range(roop): #n乗まで実施\n        print('ループ回数 {0}'.format(ix))\n        pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 \n        print('推移確率 {0}'.format(pn))\n        for i in range(len(pn)):\n            for j in range(i+1, len(pn)):\n                if(pn[i][j] > th and pn[j][i] > th): #推移確率が閾値より大きいかチェック\n                    #3. communicateだった場合\n                    print('Communicate {0} <-> {1}'.format(i, j))\n                    find = 0 \n                    for k in range(len(pn)):\n                        if i in equivalence[k]: #iが同値類k番目に存在している\n                            find = 1 #iは同値類k番目に存在\n                            if j not in equivalence[k]: #jは同値類kには存在しない\n                                equivalence[k].append(j) #jを追加        \n 

In [5]:
"""
def getEquivalence3(th, roop, p):
  reachable = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
  equivalence = [[] for i in range(len(p))] #同値類を最大数用意
  list_number = 0

  for ix in range(roop): #n乗まで実施
    pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
    for i in range(len(pn)):
      for j in range(len(pn)):
        if(pn[i][j] > th): #推移確率が閾値より大きいかチェック
          reachable[i,j] = 1

  print('到達行列 = \n{0}'.format(reachable))
#  communicate = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
#  for i in range(len(reachable)):
#    for j in range(len(reachable)):
#      if(reachable[i][j] == 1 and reachable[j][i] == 1):
    
  for i in range(len(pn)):
    for j in range(i+1, len(pn)):
      if(reachable[i][j] == 1 and reachable[j][i] == 1):
        print('reachable {0} <-> {1}'.format(i, j))
        find = 0
        for k in range(len(pn)):
          if i in equivalence[k]: #iが同値類k番目に存在している
            find = 1 #iは同値類k番目に存在
            if j not in equivalence[k]: #jは同値類kには存在しない
              equivalence[k].append(j) #jを追加
              print('{0}に{1}を追加'.format(equivalence[k], j))
              print('リスト全体 {0}'.format(equivalence))     
              break   
          if j in equivalence[k]: 
            find = 1 
            if i not in equivalence[k]:
              equivalence[k].append(i)
              print('{0}に{1}を追加'.format(equivalence[k], i))
              print('リスト全体 {0}'.format(equivalence))         
              break
        if(find == 0): #新規に追加
          equivalence[list_number].append(i)
          print('{0}に{1}を追加'.format(equivalence[k], i))
          print('リスト全体 {0}'.format(equivalence))
          if(i != j):
            equivalence[list_number].append(j)
            print('{0}に{1}を追加'.format(equivalence[k], j))
            print('リスト全体 {0}'.format(equivalence))
          list_number += 1

  #4. Communicateにならないノードを登録
  for i in range(len(pn)):
    find = 0
    for j in range(len(pn)):
      if i in equivalence[j]:
        find = 1
        break
    if find == 0:
      equivalence[list_number].append(i)
      list_number += 1

  #5. エルゴード性の確認(class数が1のとき)
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      class_number += 1

  modify_class_number = class_number
  for i in range(class_number):
    for j in range(i+1, class_number):
      s1 = set(equivalence[i])
      s2 = set(equivalence[j])
      if s1 & s2 :
        print('重複 {0} & {1}'.format(i, j))
        print('重複ノード {}'.format(s1 & s2))
        equivalence[i] = equivalence[i] + equivalence[j]
        equivalence[j].clear()
        modify_class_number -= 1

  #print('修正クラス数 {0}'.format(modify_class_number))
  for i in range(class_number):
  #  print(equivalence[i])
    equivalence[i] =list(set(equivalence[i]))
  
  return equivalence, modify_class_number
"""

"\ndef getEquivalence3(th, roop, p):\n  reachable = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意\n  equivalence = [[] for i in range(len(p))] #同値類を最大数用意\n  list_number = 0\n\n  for ix in range(roop): #n乗まで実施\n    pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 \n    for i in range(len(pn)):\n      for j in range(len(pn)):\n        if(pn[i][j] > th): #推移確率が閾値より大きいかチェック\n          reachable[i,j] = 1\n\n  print('到達行列 = \n{0}'.format(reachable))\n#  communicate = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意\n#  for i in range(len(reachable)):\n#    for j in range(len(reachable)):\n#      if(reachable[i][j] == 1 and reachable[j][i] == 1):\n    \n  for i in range(len(pn)):\n    for j in range(i+1, len(pn)):\n      if(reachable[i][j] == 1 and reachable[j][i] == 1):\n        print('reachable {0} <-> {1}'.format(i, j))\n        find = 0\n        for k in range(len(pn)):\n          if i in equivalence[k]: #iが同値類k番目に存在している\n            find = 1 #iは同値類k番目に存在\n            if j not in equivalence[

In [27]:
def getEquivalence4(th, roop, p):
  reachable = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
  equivalence = [[] for i in range(len(p))] #同値類を最大数用意
  list_number = 0

  for ix in range(roop): #n乗まで実施
    pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
    for i in range(len(pn)):
      for j in range(len(pn)):
        if(pn[i][j] > th): #推移確率が閾値より大きいかチェック
          reachable[i,j] = 1

#  print('到達行列 = \n{0}'.format(reachable))
#  communicate = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
#  for i in range(len(reachable)):
#    for j in range(len(reachable)):
#      if(reachable[i][j] == 1 and reachable[j][i] == 1):
    
  for i in range(len(pn)):
    for j in range(i+1, len(pn)):
      if(reachable[i][j] == 1 and reachable[j][i] == 1):
#        print('reachable {0} <-> {1}'.format(i, j))
        find = 0 #iでfind -> 1, jでfind -> 2
        idx = len(pn)
        for k in range(len(pn)):
          if i in equivalence[k]: #iが同値類k番目に存在している
            find = 1 #iは同値類k番目に存在
            idx = k
#            print('{0} find in {1}'.format(i, equivalence[k]))
            break
          elif j in equivalence[k]: 
            find = 2
            idx = k
#            print('{0} find in {1}'.format(j, equivalence[k]))
            break
        if find == 1:
          if j not in equivalence[idx]: #jは同値類kには存在しない (他のリストにもないことを確認する!!!他のリストにあった場合は移動がいい？ -> communicateがずれないように最後に集合で演算する)
            equivalence[idx].append(j) #jを追加
#            print('{0}に{1}を追加'.format(equivalence[idx], j))
#            print('リスト全体 {0}'.format(equivalence))     
            #break   
        elif find == 2:
          if i not in equivalence[idx]: #(他のリストにもないことを確認する!!!)
            equivalence[idx].append(i)
#            print('{0}に{1}を追加'.format(equivalence[idx], i))
#            print('リスト全体 {0}'.format(equivalence))         
            #break
        elif(find == 0): #新規に追加
          equivalence[list_number].append(i)
#          print('{0}に{1}を追加'.format(equivalence[list_number], i))
#          print('リスト全体 {0}'.format(equivalence))
          if(i != j):
            equivalence[list_number].append(j)
#            print('{0}に{1}を追加'.format(equivalence[list_number], j))
#            print('リスト全体 {0}'.format(equivalence))
          list_number += 1

  #4. Communicateにならないノードを登録
  for i in range(len(pn)):
    find = 0
    for j in range(len(pn)):
      if i in equivalence[j]:
        find = 1
        break
    if find == 0:
      equivalence[list_number].append(i)
#      print('Non Communication node {0} add'.format(i))
#      print('リスト全体 {0}'.format(equivalence))
      list_number += 1

  #5. エルゴード性の確認(class数が1のとき)
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
#      print('クラスの長さ : {0}, {1}'.format(len(equivalence[i]), equivalence[i]))
      class_number += 1

  for i in range(class_number):
    for j in range(i+1, class_number):
      s1 = set(equivalence[i])
      s2 = set(equivalence[j])
      if s1 & s2 :
#        print('重複 {0} & {1}'.format(i, j))
#        print('重複ノード {}'.format(s1 & s2))
        equivalence[i] = equivalence[i] + equivalence[j]
        equivalence[j].clear()

  #print('修正クラス数 {0}'.format(modify_class_number))
  for i in range(class_number):
  #  print(equivalence[i])
    equivalence[i] =list(set(equivalence[i]))

  #再度クラス数チェック
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      class_number += 1
  
  #再度リストを構成
  modify_equivalence = [[] for i in range(class_number)] #同値類をクラス数用意
  l_index = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      modify_equivalence[l_index] = equivalence[i]
      l_index += 1

  return modify_equivalence, class_number, reachable

In [10]:
def getDegreeMax(equivalence, reachable):
  degree_max_value = [] #クラスの中で最大次数のものをクラス0から順番に入れる
  degree_max_index = []
  reachable_sum = np.sum(reachable, axis=0) + np.sum(reachable, axis=1) #到達行列から行和と列和の和
  for i in range(len(equivalence)): #クラス数だけ回す
    deg_max = -1 #最大値の初期値
    deg_max_index = -1 #最大値を持つノード番号
    for j in equivalence[i]: #ノード番号を一つずつ取り出す
      if deg_max < reachable_sum[j]:
        deg_max = reachable_sum[j]
        deg_index = j
    degree_max_value.append(deg_max)
    degree_max_index.append(deg_index)
  return degree_max_index, degree_max_value

In [32]:
def getNormalize(p, degree_max_index, p_plus = 0.01):
  for i in degree_max_index:
    for j in degree_max_index:
      if i != j: #(i,j),(j,i)両方に足す
        p[i][j] += p_plus 
  #推移確率に直す
  for i, val in enumerate(np.sum(p, axis=1)):
    p[i] /= val
  return p

In [30]:
N = 33
#delta = 1 / N * 1.5
delta = 0.045
roop = 1
pr = getTransitionProbability(N)
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 : {0}'.format(class_number))
for i in range(class_number):
  print(equivalence[i])
#print('到達行列 \n {0}'.format(reachable))

#各クラスで次数が一番大きいノードを求める
#print('到達行列の各ノードの列和 : {0}'.format(np.sum(reachable, axis=0)))
#print('到達行列の各ノードの行和 : {0}'.format(np.sum(reachable, axis=1)))
#print('到達行列の各ノードの列和と行和の和 : {0}'.format(np.sum(reachable, axis=0) + np.sum(reachable, axis=1)))
degree_max_index, degree_max_value = getDegreeMax(equivalence, reachable)
print('各クラスの最大次数を持つノード番号 : {0}'.format(degree_max_index))
print('各クラスの最大次数 : {0}'.format(degree_max_value))
print('\n')

print('2回目')
pr = getNormalize(pr, degree_max_index)
print(pr)
#print('推移行列の各ノードの行和 : {0}'.format(np.sum(pr, axis=1)))
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 : {0}'.format(class_number))
for i in range(class_number):
  print(equivalence[i])
#print('到達行列 \n {0}'.format(reachable))

#各クラスで次数が一番大きいノードを求める
#print('到達行列の各ノードの列和 : {0}'.format(np.sum(reachable, axis=0)))
#print('到達行列の各ノードの行和 : {0}'.format(np.sum(reachable, axis=1)))
#print('到達行列の各ノードの列和と行和の和 : {0}'.format(np.sum(reachable, axis=0) + np.sum(reachable, axis=1)))
degree_max_index, degree_max_value = getDegreeMax(equivalence, reachable)
print('各クラスの最大次数を持つノード番号 : {0}'.format(degree_max_index))
print('各クラスの最大次数 : {0}'.format(degree_max_value))

print('\n')
print('3回目')
pr = getNormalize(pr, degree_max_index)
print(pr)
#print('推移行列の各ノードの行和 : {0}'.format(np.sum(pr, axis=1)))
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 : {0}'.format(class_number))
for i in range(class_number):
  print(equivalence[i])
#print('到達行列 \n {0}'.format(reachable))

#各クラスで次数が一番大きいノードを求める
#print('到達行列の各ノードの列和 : {0}'.format(np.sum(reachable, axis=0)))
#print('到達行列の各ノードの行和 : {0}'.format(np.sum(reachable, axis=1)))
#print('到達行列の各ノードの列和と行和の和 : {0}'.format(np.sum(reachable, axis=0) + np.sum(reachable, axis=1)))
degree_max_index, degree_max_value = getDegreeMax(equivalence, reachable)
print('各クラスの最大次数を持つノード番号 : {0}'.format(degree_max_index))
print('各クラスの最大次数 : {0}'.format(degree_max_value))

クラス数 : 5
[0, 1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 15, 17, 18, 19, 20, 21, 23, 24, 26, 27, 28, 29, 30, 31, 32]
[16, 6, 14]
[8]
[22]
[25]
各クラスの最大次数を持つノード番号 : [4, 16, 8, 22, 25]
各クラスの最大次数 : [21.0, 19.0, 11.0, 10.0, 13.0]


2回目
[[0.0342817  0.05479923 0.00971581 ... 0.03255038 0.03824982 0.00932918]
 [0.0065668  0.02200224 0.04829155 ... 0.0201009  0.02303496 0.00706743]
 [0.04080873 0.0520351  0.01701167 ... 0.01010971 0.05514611 0.02343893]
 ...
 [0.04355396 0.01135507 0.07118453 ... 0.04604735 0.04216115 0.038905  ]
 [0.01677558 0.05958439 0.03692481 ... 0.04019156 0.02689343 0.0080098 ]
 [0.01657453 0.03397746 0.0581662  ... 0.02925876 0.03683312 0.01505681]]
クラス数 : 5
[0, 1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 15, 17, 18, 19, 20, 21, 23, 24, 26, 27, 28, 29, 30, 31, 32]
[16, 6, 14]
[8]
[22]
[25]
各クラスの最大次数を持つノード番号 : [4, 16, 8, 22, 25]
各クラスの最大次数 : [21.0, 19.0, 11.0, 10.0, 13.0]


3回目
[[0.0342817  0.05479923 0.00971581 ... 0.03255038 0.03824982 0.00932918]
 [0.0065668  0.02200224 0.04829155 

In [38]:
N = 33
delta = 1 / N * 1.5
#delta = 0.045
roop = 1
p_plus = 0.001
roop_num = 20
pr = getTransitionProbability(N)

for i in range(roop_num):
  print('{0}回目'.format(i))
  equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
  print('クラス数 : {0}'.format(class_number))
  for i in range(class_number):
    print(equivalence[i])
  degree_max_index, degree_max_value = getDegreeMax(equivalence, reachable)
  print('各クラスの最大次数を持つノード番号 : {0}'.format(degree_max_index))
  print('各クラスの最大次数 : {0}'.format(degree_max_value))
  pr = getNormalize(pr, degree_max_index)
  print('\n')

0回目
クラス数 : 9
[0, 13, 14]
[1, 2, 4, 5, 6, 9, 10, 12, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31]
[3]
[7]
[8]
[11]
[20]
[28]
[32]
各クラスの最大次数を持つノード番号 : [13, 19, 3, 7, 8, 11, 20, 28, 32]
各クラスの最大次数 : [13.0, 22.0, 9.0, 11.0, 12.0, 17.0, 17.0, 14.0, 9.0]


1回目
クラス数 : 8
[0, 14]
[1, 2, 4, 5, 6, 9, 10, 12, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31]
[11, 20, 28]
[3]
[7]
[8]
[13]
[32]
各クラスの最大次数を持つノード番号 : [0, 19, 11, 3, 7, 8, 13, 32]
各クラスの最大次数 : [10.0, 21.0, 20.0, 10.0, 12.0, 11.0, 13.0, 9.0]


2回目
クラス数 : 6
[0, 14]
[1, 2, 4, 5, 6, 9, 10, 11, 12, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32]
[3, 7]
[20, 28]
[8]
[13]
各クラスの最大次数を持つノード番号 : [0, 11, 7, 20, 8, 13]
各クラスの最大次数 : [12.0, 21.0, 11.0, 18.0, 10.0, 13.0]


3回目
クラス数 : 7
[0, 14]
[1, 2, 4, 5, 6, 9, 10, 12, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32]
[11, 20, 13]
[3]
[7]
[8]
[28]
各クラスの最大次数を持つノード番号 : [0, 19, 11, 3, 7, 8, 28]
各クラスの最大次数 : [13.0, 20.0, 22.0, 9.0, 9.0, 9.0, 11.0]


4回目
クラ

In [ ]:
# ROSS P195 Example 4.14
# this Markov chain is irreducible
pr = np.array([[1/2, 1/2, 0], [1/2, 1/4, 1/4], [0, 1/3, 2/3]])
print(pr)
#delta = 1 / len(pr)
delta = 0
roop = 2
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

pr_n = np.linalg.matrix_power(pr, 30)
print(pr_n)
init = [ 1/ len(pr_n) for i in range(len(pr_n))]
pi = np.dot(init, pr_n)
print(pi)

In [ ]:
#ROSS P196 Example 4.15
# The classes of this Markov chain are {0,1}, {2}, and {3}
pr = np.array([[1/2, 1/2, 0, 0], [1/2, 1/2, 0, 0], [1/4, 1/4, 1/4, 1/4], [0, 0, 0, 1]])
print(pr)
delta = 0
roop = 4
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

pr_n = np.linalg.matrix_power(pr, 30)
print(pr_n)
init = [ 1/ len(pr_n) for i in range(len(pr_n))]
pi = np.dot(init, pr_n)
print(pi)

In [ ]:
#ROSS P198 Example 4.16
# all states communicate.
pr = np.array([[0, 0, 1/2, 1/2], [1, 0, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0]])
#この行列は3回以上で完全な到達となる。２回では間接的な到達
print(pr)
delta = 0
roop = 2
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

In [ ]:
# Ross P198 Example 4.17
# This chain consists of the three classes {0,1}, {2,3}, and {4}
pr = np.array([[1/2, 1/2, 0, 0, 0], [1/2, 1/2, 0, 0, 0], [0, 0, 1/2, 1/2, 0], [0, 0, 1/2, 1/2, 0], [1/4, 1/4, 0, 0, 1/2]])
print(pr)
delta = 0
roop = 10
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))