In [3]:
import numpy as np
from numpy.linalg import solve
import pandas as pd
import time
import sys
import csv
import math
import datetime
import itertools
import psutil
import random

In [4]:
def getTransitionProbability(N, R = 1):
    pr = np.zeros((R * N, R * N))
    for r in range(R):
        class_number = 0
        p = np.random.rand(N, N)
        for i, val in enumerate(np.sum(p, axis=1)):
            p[i] /= val
        for i in range(N):
            for j in range(N):
                pr[r * N+i,r * N+j] = p[i,j]
    return pr

In [45]:
"""
def getEquivalence(th, roop, p):
    list_number = 0 #空のリストを最初から使用する

    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)
    equivalence = [[] for i in range(len(p))] #同値類を最大数用意
    
    #2.Comunicationか判定して、Commnicateの場合リストに登録
    for ix in range(roop): #n乗まで実施
        p = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
        for i in range(len(p)):
            for j in range(i+1, len(p)):
                if(p[i][j] > th and p[j][i] > th): #推移確率が閾値より大きいかチェック
                    #3. communicateだった場合
                    find = 0 
                    for k in range(len(p)):
                        if i in equivalence[k]: #iが同値類k番目に存在している
                            find = 1 #iは同値類k番目に存在
                            if j not in equivalence[k]: #jは同値類kには存在しない
                                equivalence[k].append(j) #jを追加        
                            break
                        if j in equivalence[k]: 
                            find = 1 
                            if i not in equivalence[k]:
                                equivalence[k].append(i)        
                            break
                    if(find == 0): #新規に追加
                        equivalence[list_number].append(i)
                        if(i != j):
                            equivalence[list_number].append(j)
                        list_number += 1

    #4. Communicateにならないノードを登録
    for i in range(len(p)):
        find = 0
        for j in range(len(p)):
            if i in equivalence[j]:
                find = 1
                break
        if find == 0:
            equivalence[list_number].append(i)
            list_number += 1

    #5. エルゴード性の確認(class数が1のとき)
    class_number = 0
    for i in range(len(p)):
        if len(equivalence[i]) > 0:
            class_number += 1

    return equivalence, class_number
"""

'\ndef getEquivalence(th, roop, p):\n    list_number = 0 #空のリストを最初から使用する\n\n    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)\n    equivalence = [[] for i in range(len(p))] #同値類を最大数用意\n    \n    #2.Comunicationか判定して、Commnicateの場合リストに登録\n    for ix in range(roop): #n乗まで実施\n        p = np.linalg.matrix_power(p.copy(), ix+1) #累乗 \n        for i in range(len(p)):\n            for j in range(i+1, len(p)):\n                if(p[i][j] > th and p[j][i] > th): #推移確率が閾値より大きいかチェック\n                    #3. communicateだった場合\n                    find = 0 \n                    for k in range(len(p)):\n                        if i in equivalence[k]: #iが同値類k番目に存在している\n                            find = 1 #iは同値類k番目に存在\n                            if j not in equivalence[k]: #jは同値類kには存在しない\n                                equivalence[k].append(j) #jを追加        \n                            break\n                        if j in equivalence[k]: \n                            find = 1 \n                            

In [46]:
"""
def getEquivalence2(th, roop, p):
    list_number = 0 #空のリストを最初から使用する

    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)
    equivalence = [[] for i in range(len(p))] #同値類を最大数用意
    
    #2.Comunicationか判定して、Commnicateの場合リストに登録
    for ix in range(roop): #n乗まで実施
        print('ループ回数 {0}'.format(ix))
        pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
        print('推移確率 {0}'.format(pn))
        for i in range(len(pn)):
            for j in range(i+1, len(pn)):
                if(pn[i][j] > th and pn[j][i] > th): #推移確率が閾値より大きいかチェック
                    #3. communicateだった場合
                    print('Communicate {0} <-> {1}'.format(i, j))
                    find = 0 
                    for k in range(len(pn)):
                        if i in equivalence[k]: #iが同値類k番目に存在している
                            find = 1 #iは同値類k番目に存在
                            if j not in equivalence[k]: #jは同値類kには存在しない
                                equivalence[k].append(j) #jを追加        
                            break
                        if j in equivalence[k]: 
                            find = 1 
                            if i not in equivalence[k]:
                                equivalence[k].append(i)        
                            break
                    if(find == 0): #新規に追加
                        equivalence[list_number].append(i)
                        if(i != j):
                            equivalence[list_number].append(j)
                        list_number += 1

    #4. Communicateにならないノードを登録
    for i in range(len(pn)):
        find = 0
        for j in range(len(pn)):
            if i in equivalence[j]:
                find = 1
                break
        if find == 0:
            equivalence[list_number].append(i)
            list_number += 1

    #5. エルゴード性の確認(class数が1のとき)
    class_number = 0
    for i in range(len(p)):
        if len(equivalence[i]) > 0:
            class_number += 1

    return equivalence, class_number
"""

"\ndef getEquivalence2(th, roop, p):\n    list_number = 0 #空のリストを最初から使用する\n\n    #1. 空のリストを作成して、ノードを追加しておく(作成するのはノード数分)\n    equivalence = [[] for i in range(len(p))] #同値類を最大数用意\n    \n    #2.Comunicationか判定して、Commnicateの場合リストに登録\n    for ix in range(roop): #n乗まで実施\n        print('ループ回数 {0}'.format(ix))\n        pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 \n        print('推移確率 {0}'.format(pn))\n        for i in range(len(pn)):\n            for j in range(i+1, len(pn)):\n                if(pn[i][j] > th and pn[j][i] > th): #推移確率が閾値より大きいかチェック\n                    #3. communicateだった場合\n                    print('Communicate {0} <-> {1}'.format(i, j))\n                    find = 0 \n                    for k in range(len(pn)):\n                        if i in equivalence[k]: #iが同値類k番目に存在している\n                            find = 1 #iは同値類k番目に存在\n                            if j not in equivalence[k]: #jは同値類kには存在しない\n                                equivalence[k].append(j) #jを追加        \n 

In [7]:
"""
def getEquivalence3(th, roop, p):
  reachable = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
  equivalence = [[] for i in range(len(p))] #同値類を最大数用意
  list_number = 0

  for ix in range(roop): #n乗まで実施
    pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
    for i in range(len(pn)):
      for j in range(len(pn)):
        if(pn[i][j] > th): #推移確率が閾値より大きいかチェック
          reachable[i,j] = 1

  print('到達行列 = \n{0}'.format(reachable))
#  communicate = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
#  for i in range(len(reachable)):
#    for j in range(len(reachable)):
#      if(reachable[i][j] == 1 and reachable[j][i] == 1):
    
  for i in range(len(pn)):
    for j in range(i+1, len(pn)):
      if(reachable[i][j] == 1 and reachable[j][i] == 1):
        print('reachable {0} <-> {1}'.format(i, j))
        find = 0
        for k in range(len(pn)):
          if i in equivalence[k]: #iが同値類k番目に存在している
            find = 1 #iは同値類k番目に存在
            if j not in equivalence[k]: #jは同値類kには存在しない
              equivalence[k].append(j) #jを追加
              print('{0}に{1}を追加'.format(equivalence[k], j))
              print('リスト全体 {0}'.format(equivalence))     
              break   
          if j in equivalence[k]: 
            find = 1 
            if i not in equivalence[k]:
              equivalence[k].append(i)
              print('{0}に{1}を追加'.format(equivalence[k], i))
              print('リスト全体 {0}'.format(equivalence))         
              break
        if(find == 0): #新規に追加
          equivalence[list_number].append(i)
          print('{0}に{1}を追加'.format(equivalence[k], i))
          print('リスト全体 {0}'.format(equivalence))
          if(i != j):
            equivalence[list_number].append(j)
            print('{0}に{1}を追加'.format(equivalence[k], j))
            print('リスト全体 {0}'.format(equivalence))
          list_number += 1

  #4. Communicateにならないノードを登録
  for i in range(len(pn)):
    find = 0
    for j in range(len(pn)):
      if i in equivalence[j]:
        find = 1
        break
    if find == 0:
      equivalence[list_number].append(i)
      list_number += 1

  #5. エルゴード性の確認(class数が1のとき)
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      class_number += 1

  modify_class_number = class_number
  for i in range(class_number):
    for j in range(i+1, class_number):
      s1 = set(equivalence[i])
      s2 = set(equivalence[j])
      if s1 & s2 :
        print('重複 {0} & {1}'.format(i, j))
        print('重複ノード {}'.format(s1 & s2))
        equivalence[i] = equivalence[i] + equivalence[j]
        equivalence[j].clear()
        modify_class_number -= 1

  #print('修正クラス数 {0}'.format(modify_class_number))
  for i in range(class_number):
  #  print(equivalence[i])
    equivalence[i] =list(set(equivalence[i]))
  
  return equivalence, modify_class_number
"""

In [33]:
def getEquivalence4(th, roop, p):
  reachable = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
  equivalence = [[] for i in range(len(p))] #同値類を最大数用意
  list_number = 0

  for ix in range(roop): #n乗まで実施
    pn = np.linalg.matrix_power(p.copy(), ix+1) #累乗 
    for i in range(len(pn)):
      for j in range(len(pn)):
        if(pn[i][j] > th): #推移確率が閾値より大きいかチェック
          reachable[i,j] = 1

  print('到達行列 = \n{0}'.format(reachable))
#  communicate = np.zeros((len(p), len(p))) #全て0のpと同じ大きさの行列を用意
#  for i in range(len(reachable)):
#    for j in range(len(reachable)):
#      if(reachable[i][j] == 1 and reachable[j][i] == 1):
    
  for i in range(len(pn)):
    for j in range(i+1, len(pn)):
      if(reachable[i][j] == 1 and reachable[j][i] == 1):
        print('reachable {0} <-> {1}'.format(i, j))
        find = 0 #iでfind -> 1, jでfind -> 2
        idx = len(pn)
        for k in range(len(pn)):
          if i in equivalence[k]: #iが同値類k番目に存在している
            find = 1 #iは同値類k番目に存在
            idx = k
            print('{0} find in {1}'.format(i, equivalence[k]))
            break
          elif j in equivalence[k]: 
            find = 2
            idx = k
            print('{0} find in {1}'.format(j, equivalence[k]))
            break
        if find == 1:
          if j not in equivalence[idx]: #jは同値類kには存在しない (他のリストにもないことを確認する!!!他のリストにあった場合は移動がいい？ -> communicateがずれないように最後に集合で演算する)
            equivalence[idx].append(j) #jを追加
            print('{0}に{1}を追加'.format(equivalence[idx], j))
            print('リスト全体 {0}'.format(equivalence))     
            #break   
        elif find == 2:
          if i not in equivalence[idx]: #(他のリストにもないことを確認する!!!)
            equivalence[idx].append(i)
            print('{0}に{1}を追加'.format(equivalence[idx], i))
            print('リスト全体 {0}'.format(equivalence))         
            #break
        elif(find == 0): #新規に追加
          equivalence[list_number].append(i)
          print('{0}に{1}を追加'.format(equivalence[list_number], i))
          print('リスト全体 {0}'.format(equivalence))
          if(i != j):
            equivalence[list_number].append(j)
            print('{0}に{1}を追加'.format(equivalence[list_number], j))
            print('リスト全体 {0}'.format(equivalence))
          list_number += 1

  #4. Communicateにならないノードを登録
  for i in range(len(pn)):
    find = 0
    for j in range(len(pn)):
      if i in equivalence[j]:
        find = 1
        break
    if find == 0:
      equivalence[list_number].append(i)
      print('Non Communication node {0} add'.format(i))
      print('リスト全体 {0}'.format(equivalence))
      list_number += 1

  #5. エルゴード性の確認(class数が1のとき)
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      print('クラスの長さ : {0}, {1}'.format(len(equivalence[i]), equivalence[i]))
      class_number += 1

  for i in range(class_number):
    for j in range(i+1, class_number):
      s1 = set(equivalence[i])
      s2 = set(equivalence[j])
      if s1 & s2 :
        print('重複 {0} & {1}'.format(i, j))
        print('重複ノード {}'.format(s1 & s2))
        equivalence[i] = equivalence[i] + equivalence[j]
        equivalence[j].clear()

  #print('修正クラス数 {0}'.format(modify_class_number))
  for i in range(class_number):
  #  print(equivalence[i])
    equivalence[i] =list(set(equivalence[i]))

  #再度クラス数チェック
  class_number = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      class_number += 1
  
  #再度リストを構成
  modify_equivalence = [[] for i in range(class_number)] #同値類をクラス数用意
  l_index = 0
  for i in range(len(pn)):
    if len(equivalence[i]) > 0:
      modify_equivalence[l_index] = equivalence[i]
      l_index += 1

  return modify_equivalence, class_number, reachable

In [34]:
N = 33
#delta = 1 / N
delta = 0.045
roop = 1
pr = getTransitionProbability(N)
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 : {0}'.format(class_number))
for i in range(class_number):
  print(equivalence[i])
print('到達行列 \n {0}'.format(reachable))

到達行列 = 
[[0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]
reachable 0 <-> 5
[0]に0を追加
リスト全体 [[0], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
[0, 5]に5を追加
リスト全体 [[0, 5], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
reachable 0 <-> 6
0 find in [0, 5]
[0, 5, 6]に6を追加
リスト全体 [[0, 5, 6], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
reachable 0 <-> 12
0 find in [0, 5, 6]
[0, 5, 6, 12]に12を追加
リスト全体 [[0, 5, 6, 12], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
reachable 0 <-> 31
0 find in [0, 5, 6, 12]
[0, 5, 6, 12, 31]に31を追加
リスト全体 [[0, 5, 6, 12, 31], [], [], [], [], 

In [37]:
# ROSS P195 Example 4.14
# this Markov chain is irreducible
pr = np.array([[1/2, 1/2, 0], [1/2, 1/4, 1/4], [0, 1/3, 2/3]])
print(pr)
#delta = 1 / len(pr)
delta = 0
roop = 2
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

pr_n = np.linalg.matrix_power(pr, 30)
print(pr_n)
init = [ 1/ len(pr_n) for i in range(len(pr_n))]
pi = np.dot(init, pr_n)
print(pi)

[[0.5        0.5        0.        ]
 [0.5        0.25       0.25      ]
 [0.         0.33333333 0.66666667]]
到達行列 = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
reachable 0 <-> 1
[0]に0を追加
リスト全体 [[0], [], []]
[0, 1]に1を追加
リスト全体 [[0, 1], [], []]
reachable 0 <-> 2
0 find in [0, 1]
[0, 1, 2]に2を追加
リスト全体 [[0, 1, 2], [], []]
reachable 1 <-> 2
1 find in [0, 1, 2]
クラスの長さ : 3, [0, 1, 2]
クラス数 = 1
クラス ID = 0
[0, 1, 2]
到達行列 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.36363654 0.36363641 0.27272705]
 [0.36363641 0.36363637 0.27272722]
 [0.36363607 0.36363629 0.27272764]]
[0.36363634 0.36363636 0.2727273 ]


In [41]:
#ROSS P196 Example 4.15
# The classes of this Markov chain are {0,1}, {2}, and {3}
pr = np.array([[1/2, 1/2, 0, 0], [1/2, 1/2, 0, 0], [1/4, 1/4, 1/4, 1/4], [0, 0, 0, 1]])
print(pr)
delta = 0
roop = 4
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

pr_n = np.linalg.matrix_power(pr, 30)
print(pr_n)
init = [ 1/ len(pr_n) for i in range(len(pr_n))]
pi = np.dot(init, pr_n)
print(pi)

[[0.5  0.5  0.   0.  ]
 [0.5  0.5  0.   0.  ]
 [0.25 0.25 0.25 0.25]
 [0.   0.   0.   1.  ]]
到達行列 = 
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]
reachable 0 <-> 1
[0]に0を追加
リスト全体 [[0], [], [], []]
[0, 1]に1を追加
リスト全体 [[0, 1], [], [], []]
Non Communication node 2 add
リスト全体 [[0, 1], [2], [], []]
Non Communication node 3 add
リスト全体 [[0, 1], [2], [3], []]
クラスの長さ : 2, [0, 1]
クラスの長さ : 1, [2]
クラスの長さ : 1, [3]
クラス数 = 3
クラス ID = 0
[0, 1]
クラス ID = 1
[2]
クラス ID = 2
[3]
到達行列 
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 1.]]
[[5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00]
 [5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00]
 [3.33333333e-01 3.33333333e-01 8.67361738e-19 3.33333333e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[3.33333333e-01 3.33333333e-01 2.16840434e-19 3.33333333e-01]


In [42]:
#ROSS P198 Example 4.16
# all states communicate.
pr = np.array([[0, 0, 1/2, 1/2], [1, 0, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0]])
#この行列は3回以上で完全な到達となる。２回では間接的な到達
print(pr)
delta = 0
roop = 2
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

[[0.  0.  0.5 0.5]
 [1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  1.  0.  0. ]]
到達行列 = 
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
reachable 0 <-> 1
[0]に0を追加
リスト全体 [[0], [], [], []]
[0, 1]に1を追加
リスト全体 [[0, 1], [], [], []]
reachable 0 <-> 2
0 find in [0, 1]
[0, 1, 2]に2を追加
リスト全体 [[0, 1, 2], [], [], []]
reachable 0 <-> 3
0 find in [0, 1, 2]
[0, 1, 2, 3]に3を追加
リスト全体 [[0, 1, 2, 3], [], [], []]
reachable 1 <-> 2
1 find in [0, 1, 2, 3]
reachable 1 <-> 3
1 find in [0, 1, 2, 3]
クラスの長さ : 4, [0, 1, 2, 3]
クラス数 = 1
クラス ID = 0
[0, 1, 2, 3]
到達行列 
 [[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [44]:
# Ross P198 Example 4.17
# This chain consists of the three classes {0,1}, {2,3}, and {4}
pr = np.array([[1/2, 1/2, 0, 0, 0], [1/2, 1/2, 0, 0, 0], [0, 0, 1/2, 1/2, 0], [0, 0, 1/2, 1/2, 0], [1/4, 1/4, 0, 0, 1/2]])
print(pr)
delta = 0
roop = 1
equivalence, class_number, reachable = getEquivalence4(delta, roop, pr)
print('クラス数 = {0}'.format(class_number))
for i in range(class_number):
  print('クラス ID = {0}'.format(i))
  print(equivalence[i])

print('到達行列 \n {0}'.format(reachable))

[[0.5  0.5  0.   0.   0.  ]
 [0.5  0.5  0.   0.   0.  ]
 [0.   0.   0.5  0.5  0.  ]
 [0.   0.   0.5  0.5  0.  ]
 [0.25 0.25 0.   0.   0.5 ]]
到達行列 = 
[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [1. 1. 0. 0. 1.]]
reachable 0 <-> 1
[0]に0を追加
リスト全体 [[0], [], [], [], []]
[0, 1]に1を追加
リスト全体 [[0, 1], [], [], [], []]
reachable 2 <-> 3
[2]に2を追加
リスト全体 [[0, 1], [2], [], [], []]
[2, 3]に3を追加
リスト全体 [[0, 1], [2, 3], [], [], []]
Non Communication node 4 add
リスト全体 [[0, 1], [2, 3], [4], [], []]
クラスの長さ : 2, [0, 1]
クラスの長さ : 2, [2, 3]
クラスの長さ : 1, [4]
クラス数 = 3
クラス ID = 0
[0, 1]
クラス ID = 1
[2, 3]
クラス ID = 2
[4]
到達行列 
 [[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [1. 1. 0. 0. 1.]]
